### ISSUE TITLE
materialize parallax

### ISSUE THREAD

**Issue by m7marius7** [Smip/ngx-materialize#1]
Hi,
I know isn't an issue, but please add parallax too. 
Thank you very very mutch.

**Comment by Smip** [comment]
Hi,
Thanks  for your message.
I took the task to work.

**Comment by Smip** [comment]
> Hi,
> I know isn't an issue, but please add parallax too.
> Thank you very very mutch.

Added `mParallax`

**Comment by m7marius7** [comment]
Thank you man,
You're the best.
