### ISSUE TITLE
Angular 8 universal NgxMaterialize

### ISSUE THREAD

**Issue by m7marius7** [Smip/ngx-materialize#2]
Hi, 
I added @nguniversal/express-engine --clientProject in my project. I use materialize and when I build:ssr I have this error:
"Couldn't find M object on window. It is created by the materialize-css library. Please import materialize-css before importing ngx-materialize."

Please help me with this

Thank you very much!

**Comment by Smip** [comment]
Hi, You can ignore this message. This message does not affect the application. I'll try fix it in the future build. Thanks.

**Comment by Smip** [comment]
@m7marius7 
Please update library with `npm i -S @smip/ngx-materialize`
If you will have new issue feel free to create new or re-open this one.

**Comment by m7marius7** [comment]
Wow! Thank you so much. It's working. You are the best!!!
